version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: unwetter_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test123!
    ports:
      - "1433:1433"
    volumes:
      - ./docker/init.sql:/init.sql

  sqlcmd:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    entrypoint: >
      /bin/bash -c "
        sleep 20 && 
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U SA -P 'Test123!' -i /init.sql
      "
    volumes:
      - ./docker/init.sql:/init.sql
